name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
